"""Corpus slideshow component — presentation deck of the WildChat analysis.

The slideshow is the "companion exhibit" to the live TEDx talk. It walks
through the full corpus analysis: headline stat, theme distribution,
emotion-by-theme heatmap, UMAP map, curiosity finding, cross-corpus
comparison, influence-at-scale drill, live audience overlay, and three
Sonnet-written literary vignettes.

The actual slide PNGs live in `corpus/out/slides/` and are generated by
`corpus/slides_main.py`, `cross_corpus.py`, `drill_influence.py`,
`audience_overlay.py`, and `vignettes.py`.
"""
from __future__ import annotations

import html as _html
from pathlib import Path

HERE = Path(__file__).parent
SLIDES_DIR = HERE.parent / "corpus" / "out" / "slides"

# Presentation order. Each entry is (file, chapter, caption).
# Chapter groups slides thematically. Caption is a 1-line descriptor.
SLIDES: list[dict] = [
    {
        "file": "12_answer_warmth.png",
        "chapter": "The data",
        "caption": "RLHF made visible — the AI fills the emotional vacuum.",
    },
    {
        "file": "14_mirror_matrix.png",
        "chapter": "The data",
        "caption": "No matter what you bring, you get approval back.",
    },
    {
        "file": "15_gpt_vs_claude.png",
        "chapter": "The data",
        "caption": "It's not one model. It's the architecture.",
    },
    {
        "file": "13_answer_vocabulary.png",
        "chapter": "The data",
        "caption": "Presence without judgment, quantified.",
    },
]


def slide_count() -> int:
    return len(SLIDES)


def slide_path(idx: int) -> str:
    """Return absolute path to the slide PNG for index `idx`."""
    idx = max(0, min(idx, len(SLIDES) - 1))
    return str(SLIDES_DIR / SLIDES[idx]["file"])


def slides_dir() -> str:
    return str(SLIDES_DIR)


def slide_html(idx: int) -> str:
    """Return a full HTML block: chapter chrome + slide image + keyboard hint.

    This bundles everything into a single gr.HTML component to sidestep
    Gradio's Image component progress-tracker quirks. The image is served
    via Gradio's /gradio_api/file= static-file endpoint (corpus/out/slides
    must be registered as an allowed_path on launch).
    """
    idx = max(0, min(idx, len(SLIDES) - 1))
    s = SLIDES[idx]
    n = len(SLIDES)
    chapter = _html.escape(s["chapter"])
    caption = _html.escape(s["caption"])
    img_path = str(SLIDES_DIR / s["file"])
    img_src = f"/gradio_api/file={img_path}"
    dots = ""
    for i in range(n):
        active = i == idx
        color = "#EC4899" if active else "#334155"
        size = "10px" if active else "6px"
        dots += (
            f'<span style="display:inline-block; width:{size}; height:{size}; '
            f'border-radius:50%; background:{color}; margin:0 4px; '
            f'transition: all 180ms ease;"></span>'
        )
    return f"""
<div style="background:#06080C; min-height:94vh; display:flex; flex-direction:column;">
  <div style="padding:1.4em 2em 0.6em; border-bottom:1px solid #1E293B;">
    <div style="max-width:1200px; margin:0 auto; display:flex; align-items:baseline; gap:2em;">
      <div style="color:#EC4899; font-size:0.82em; letter-spacing:0.22em; text-transform:uppercase; font-weight:700;">
        {chapter}
      </div>
      <div style="flex:1; color:#94A3B8; font-size:1em; font-style:italic;">
        {caption}
      </div>
      <div style="color:#64748B; font-size:0.9em; font-variant-numeric: tabular-nums;">
        {idx + 1} / {n}
      </div>
    </div>
    <div style="max-width:1200px; margin:0.8em auto 0; text-align:center; line-height:0;">
      {dots}
    </div>
  </div>
  <div style="flex:1; display:flex; align-items:center; justify-content:center; padding:1.2em 2em;">
    <img src="{img_src}" style="max-width:100%; max-height:78vh; display:block; object-fit:contain;" alt="{caption}">
  </div>
  <div style="padding:0.9em 2em 1.4em; text-align:center;">
    <div style="color:#475569; font-size:0.85em;">
      Use <kbd style="background:#1E293B; color:#94A3B8; padding:0.2em 0.6em; border-radius:4px; font-family:inherit;">&larr;</kbd>
      and <kbd style="background:#1E293B; color:#94A3B8; padding:0.2em 0.6em; border-radius:4px; font-family:inherit;">&rarr;</kbd>
      to move through the deck · {n} slides total
    </div>
  </div>
</div>
"""


def advance(idx: int) -> int:
    return min(idx + 1, len(SLIDES) - 1)


def retreat(idx: int) -> int:
    return max(idx - 1, 0)
